# Generated by Django 4.0.6 on 2024-05-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='code',
            field=models.CharField(max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
