# Generated by Django 4.0.6 on 2024-05-29 10:40

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_system_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=app.models.NameField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='code',
            field=app.models.NameField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='name',
            field=app.models.NameField(max_length=100, unique=True),
        ),
    ]
