# Generated by Django 4.0.6 on 2024-05-30 06:00

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_system_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=app.models.NameField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('name', 'system')},
        ),
    ]
