# Generated by Django 4.0.6 on 2024-05-30 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_role_unique'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role', 'system')},
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_access', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.system')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='system_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System User',
                'verbose_name_plural': 'System Users',
                'unique_together': {('user', 'system')},
            },
        ),
    ]
