# Generated by Django 4.0.6 on 2024-05-31 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_system_active'),
        ('app', '0006_system_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='system_user', to='authentication.profile'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user', to='authentication.profile'),
        ),
    ]
