# Generated by Django 4.0.6 on 2024-10-30 10:08

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_system_active'),
        ('app', '0007_changer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', app.models.NameField(max_length=512)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.system')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='authentication.profile')),
            ],
            options={
                'verbose_name': 'User Logs',
                'verbose_name_plural': 'User Logs',
            },
        ),
    ]
