# Generated by Django 4.0.6 on 2024-05-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_init'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
