# Generated by Django 4.0.6 on 2024-05-29 10:40

import authentication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_first_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=authentication.models.NameField(blank=True, default='male', max_length=10, null=True),
        ),
    ]
